image: docker:19.03.11

services:
  - docker:dind
  
before_script:
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PAT}"
  
build:
  stage: build
  script:
    - echo $DOCKER_HOST
    - docker build . -t "guardianmultimedia/pluto-userbeacon:$CI_PIPELINE_IID"
    - docker push "guardianmultimedia/pluto-userbeacon:$CI_PIPELINE_IID"
    