image: docker:19.03.11

services:
  - docker:dind
  
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  
build:
  stage: build
  script:
    - docker build . -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_IID"
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_IID"
    